import {motionTransition} from './motion-system';
import {useEffect,useRef,useState,type ButtonHTMLAttributes,type ReactNode} from 'react';
import * as Dialog from '@radix-ui/react-dialog';
import * as Menu from '@radix-ui/react-dropdown-menu';
import {AnimatePresence,motion,useReducedMotion} from 'motion/react';
import {getPeaks,playback,usePlayback} from './audio';
import {useTheme} from './theme';
import {formatTime,sourceLabel,type Track} from './domain';
import {CaretDownIcon,CopyIcon,DownloadIcon,ExpandIcon,FileAudioIcon,MoreIcon,MuteIcon,PauseIcon,PencilIcon,PlayIcon,QueueIcon,RetryIcon,SpinnerIcon,StarIcon,TrashIcon,UndoIcon,VolumeIcon,WarningIcon,XIcon} from './icons';

export function Button({className='',children,...props}:ButtonHTMLAttributes<HTMLButtonElement>){return <button type="button" className={`button ${className}`} {...props}>{children}</button>}
export function IconButton({label,children,className='',...props}:ButtonHTMLAttributes<HTMLButtonElement>&{label:string}){return <button type="button" aria-label={label} title={label} className={`icon-button ${className}`} {...props}>{children}</button>}
export function Sheet({open,onClose,title,subtitle,children,footer,wide=false,center=false,keepMounted=false}:{open:boolean;onClose:()=>void;title:string;subtitle?:string;children:ReactNode;footer?:ReactNode;wide?:boolean;center?:boolean;keepMounted?:boolean}){
  const contentRef=useRef<HTMLDivElement>(null);
  const persistedClass=keepMounted?' keep-mounted':'';
  return <Dialog.Root open={open} onOpenChange={v=>{if(!v)onClose()}}><Dialog.Portal {...(keepMounted?{forceMount:true}: {})}><Dialog.Overlay className={`dialog-backdrop${persistedClass}`}/><Dialog.Content {...(keepMounted?{forceMount:true}: {})} ref={contentRef} className={`sheet ${wide?'wide':''} ${center?'center':''}${persistedClass}`} onOpenAutoFocus={e=>{e.preventDefault();requestAnimationFrame(()=>contentRef.current?.querySelector<HTMLElement>('[data-dialog-close]')?.focus())}}>
    <header className="sheet-header"><div><Dialog.Title>{title}</Dialog.Title><Dialog.Description>{subtitle??'调整当前设置并返回工作台。'}</Dialog.Description></div><Dialog.Close asChild><IconButton label={keepMounted?'收起助手（任务继续）':'关闭面板'} data-dialog-close><XIcon/></IconButton></Dialog.Close></header>
    <div className="sheet-body">{children}</div>{footer?<footer className="sheet-footer">{footer}</footer>:null}
  </Dialog.Content></Dialog.Portal></Dialog.Root>
}
export type Notice={id:number;text:string;action?:()=>void;actionLabel?:string};
export function Toast({notice,onClose}:{notice:Notice|null;onClose:()=>void}){return <AnimatePresence>{notice?<motion.div className="toast" role="status" key={notice.id} initial={{opacity:0,y:8}} animate={{opacity:1,y:0}} exit={{opacity:0,y:4}}><span>{notice.text}</span>{notice.action?<button onClick={notice.action}>{notice.actionLabel??'撤销'}</button>:null}<IconButton label="关闭提示" onClick={onClose}><XIcon size={16}/></IconButton></motion.div>:null}</AnimatePresence>}
export function Waveform({url,progress=0,compact=false,onSeek,duration=0,disabled=false}:{url:string;progress?:number;compact?:boolean;onSeek?:(n:number)=>void;duration?:number;disabled?:boolean}){
  const theme=useTheme();
  const [peaks,setPeaks]=useState<number[]>([]),[error,setError]=useState(false);const canvas=useRef<HTMLCanvasElement>(null);
  useEffect(()=>{let active=true;setError(false);getPeaks(url).then(p=>{if(active)setPeaks(p)}).catch(()=>{if(active)setError(true)});return()=>{active=false}},[url]);
  useEffect(()=>{const el=canvas.current;if(!el)return;const draw=()=>{const rect=el.getBoundingClientRect();const ratio=Math.min(devicePixelRatio,2);el.width=rect.width*ratio;el.height=rect.height*ratio;const ctx=el.getContext('2d');if(!ctx)return;ctx.scale(ratio,ratio);ctx.clearRect(0,0,rect.width,rect.height);if(!peaks.length)return;const spacing=compact?3.6:4.4;const n=Math.floor(rect.width/spacing);for(let i=0;i<n;i++){const p=peaks[Math.floor(i/n*peaks.length)]??0;const h=Math.max(2,p*(rect.height-4));ctx.fillStyle=i/n<progress?(theme==='dark'?'rgba(222,218,214,.8)':'rgba(85,77,67,.63)'):(theme==='dark'?'rgba(149,149,159,.36)':'rgba(121,119,117,.28)');ctx.beginPath();ctx.roundRect(i*spacing,(rect.height-h)/2,compact?1.3:1.8,h,1);ctx.fill()}};draw();const ro=new ResizeObserver(draw);ro.observe(el);return()=>ro.disconnect()},[peaks,progress,compact,theme]);
  return <div className={`waveform ${compact?'compact':''} ${disabled?'disabled':''}`}><canvas ref={canvas} aria-hidden="true"/>{!peaks.length?<span className="waveform-label">{error?'波形暂不可用':'读取音频波形…'}</span>:null}{onSeek?<input type="range" min={0} max={duration||1} step=".1" value={Math.min(progress,1)*duration} onChange={e=>onSeek(Number(e.target.value))} aria-label="音频播放位置" aria-valuetext={formatTime(progress*duration)} disabled={disabled}/>:null}</div>
}
type TrackActions={onFavorite:(t:Track)=>void;onReuse:(t:Track)=>void;onRegenerate:(t:Track)=>void;onExport:(t:Track)=>void;onRename:(t:Track)=>void;onRemove:(t:Track)=>void;onRestore:(t:Track)=>void;onLocate:(t:Track)=>void;onDetails:(t:Track)=>void};
export function TrackMenu({track,actions}:{track:Track;actions:TrackActions}){
  return <Menu.Root><Menu.Trigger asChild><IconButton label={`${track.title} 的更多操作`}><MoreIcon size={25} weight="bold"/></IconButton></Menu.Trigger><Menu.Portal><Menu.Content className="dropdown" align="end" sideOffset={6}>
    <Menu.Label className="menu-label">{track.title}</Menu.Label>
    <Menu.Item onSelect={()=>actions.onDetails(track)}><FileAudioIcon/>作品详情</Menu.Item><Menu.Item onSelect={()=>actions.onFavorite(track)}><StarIcon/>{track.favorite?'取消收藏':'收藏作品'}</Menu.Item>
    <Menu.Item onSelect={()=>actions.onReuse(track)}><CopyIcon/>复用参数</Menu.Item>
    <Menu.Item onSelect={()=>actions.onRegenerate(track)}><RetryIcon/>再生成一版</Menu.Item>
    <Menu.Separator/>
    <Menu.Item onSelect={()=>actions.onRename(track)}><PencilIcon/>重命名</Menu.Item>
    {track.missing?<Menu.Item onSelect={()=>actions.onLocate(track)}><FileAudioIcon/>{track.audioKind==='generated'?'检查生成文件':'重新定位音频'}</Menu.Item>:<Menu.Item onSelect={()=>actions.onExport(track)}><DownloadIcon/>导出音频</Menu.Item>}
    <Menu.Separator/>
    <Menu.Item className="danger" onSelect={()=>actions.onRemove(track)}><TrashIcon/>永久删除作品</Menu.Item>
  </Menu.Content></Menu.Portal></Menu.Root>
}
export function ExpandedTrack({track,onReuse,onExport,onPlay,onLocate}:{track:Track;onReuse:()=>void;onExport:()=>void;onPlay:()=>void;onLocate:()=>void}){
  const audio=usePlayback();const same=audio.trackId===track.id;const duration=same?audio.duration:track.duration;const current=same?audio.current:0;
  return <div className="track-expanded"><div className="expanded-artwork"><img src={track.artwork} alt={`${track.title} 封面`}/><IconButton label={same&&audio.playing?`暂停 ${track.title}`:`播放 ${track.title}`} className="artwork-play" onClick={track.missing?onLocate:onPlay}>{track.missing?<WarningIcon/>:same&&audio.playing?<PauseIcon weight="fill"/>:<PlayIcon weight="fill"/>}</IconButton></div><div className="expanded-content"><div className="expanded-heading"><div className="title-version"><h2>{track.title}</h2><span className="version">{track.version} · {sourceLabel(track)}</span></div><div className="expanded-actions"><Button onClick={onReuse}><CopyIcon/>复用参数</Button><Button onClick={onExport} disabled={track.missing}><DownloadIcon/>导出</Button></div></div><p className="expanded-style">{track.style}</p>
    {track.missing?<div className="inline-warning"><WarningIcon/><span>音频文件不可用</span><button onClick={onLocate}>{track.audioKind==='generated'?'检查引擎':'重新定位'}</button></div>:<><Waveform url={track.audioUrl} progress={current/duration} duration={duration} onSeek={same?n=>playback.seek(n):undefined}/><div className="expanded-timeline"><span>{formatTime(current)}</span><input type="range" min={0} max={duration} step=".1" value={current} aria-label={`${track.title} 播放进度`} onChange={e=>{if(same)playback.seek(Number(e.target.value))}} disabled={!same}/><span>{formatTime(duration)}</span></div></>}
    <p className="lyric-quote">“{track.lyrics.split('\n').filter(v=>v&&!v.startsWith('[')).slice(-2).join('，')}。”</p>
  </div></div>
}
export function Player({track,onPlay,onDetails,onQueue}:{track:Track;onPlay:()=>void;onDetails:()=>void;onQueue:()=>void}){
  const s=usePlayback(),same=s.trackId===track.id;const current=same?s.current:0,duration=same?s.duration:track.duration;const [previousVolume,setPreviousVolume]=useState(.7);
  return <footer className="player glass" aria-label="全局音频播放器"><div className="player-identity"><button className="player-cover" onClick={onDetails} aria-label={`${track.title} 作品详情`}><img src={track.artwork} alt=""/></button><div><div className="title-version"><button className="player-name" onClick={onDetails}>{track.title}</button><span className="version">{track.version} · {sourceLabel(track)}</span></div><p>{track.style}</p></div></div><div className="player-controls"><IconButton label={same&&s.playing?'暂停播放':'播放音频'} className="main-play" onClick={onPlay} disabled={track.missing}>{same&&s.loading?<SpinnerIcon className="spin"/>:same&&s.playing?<PauseIcon weight="fill"/>:<PlayIcon weight="fill"/>}</IconButton><span className="player-time">{formatTime(current)}</span><div className="player-progress"><Waveform url={track.audioUrl} compact progress={current/duration} duration={duration} onSeek={same?n=>playback.seek(n):undefined} disabled={track.missing}/><input type="range" aria-label="播放器进度" min={0} max={duration} step=".1" value={current} disabled={!same||track.missing} onChange={e=>playback.seek(Number(e.target.value))}/></div><span className="player-time">{formatTime(duration)}</span></div><div className="player-end"><IconButton label={s.volume===0?'恢复音量':'静音'} onClick={()=>{if(s.volume){setPreviousVolume(s.volume);playback.volume(0)}else playback.volume(previousVolume)}}>{s.volume===0?<MuteIcon/>:<VolumeIcon/>}</IconButton><input type="range" aria-label="音量" min={0} max={1} step=".01" value={s.volume} onChange={e=>playback.volume(Number(e.target.value))}/><span className="vertical-separator"/><IconButton label="查看生成队列" onClick={onQueue}><QueueIcon/></IconButton></div></footer>
}
export function PlaybackError({onLocate}:{onLocate:()=>void}){const s=usePlayback();return <AnimatePresence initial={false}>{s.error?<motion.div key="playback-error" className="playback-error" role="alert" initial={{opacity:0,transform:'translate(-50%,6px)'}} animate={{opacity:1,transform:'translate(-50%,0)'}} exit={{opacity:0,transform:'translate(-50%,3px)',transition:{duration:.12,ease:[.4,0,1,1]}}} transition={{duration:.18,ease:[.22,1,.36,1]}}><WarningIcon/>{s.error}<button onClick={onLocate}>查看文件</button><IconButton label="关闭播放错误" onClick={()=>playback.clearError()}><XIcon/></IconButton></motion.div>:null}</AnimatePresence>}
export function Collapsible({title,children}:{title:string;children:ReactNode}){const[open,setOpen]=useState(false),reduced=useReducedMotion();return <section className="collapsible"><button onClick={()=>setOpen(v=>!v)} aria-expanded={open}>{title}<CaretDownIcon className={open?'rotate':''}/></button><AnimatePresence initial={false}>{open?<motion.div initial={{height:0,opacity:0}} animate={{height:'auto',opacity:1}} exit={{height:0,opacity:0}} transition={reduced?{duration:0}:motionTransition}>{children}</motion.div>:null}</AnimatePresence></section>}
