export {WaveformIcon as WaveformIcon} from '@phosphor-icons/react/dist/csr/Waveform';
export {MagnifyingGlassIcon as SearchIcon} from '@phosphor-icons/react/dist/csr/MagnifyingGlass';
export {GearSixIcon as SettingsIcon} from '@phosphor-icons/react/dist/csr/GearSix';
export {ListBulletsIcon as QueueIcon} from '@phosphor-icons/react/dist/csr/ListBullets';
export {CaretDownIcon} from '@phosphor-icons/react/dist/csr/CaretDown';
export {CaretUpIcon} from '@phosphor-icons/react/dist/csr/CaretUp';
export {CheckIcon} from '@phosphor-icons/react/dist/csr/Check';
export {XIcon} from '@phosphor-icons/react/dist/csr/X';
export {StarIcon} from '@phosphor-icons/react/dist/csr/Star';
export {DotsThreeIcon as MoreIcon} from '@phosphor-icons/react/dist/csr/DotsThree';
export {DownloadSimpleIcon as DownloadIcon} from '@phosphor-icons/react/dist/csr/DownloadSimple';
export {CopyIcon} from '@phosphor-icons/react/dist/csr/Copy';
export {PlayIcon} from '@phosphor-icons/react/dist/csr/Play';
export {PauseIcon} from '@phosphor-icons/react/dist/csr/Pause';
export {SpeakerHighIcon as VolumeIcon} from '@phosphor-icons/react/dist/csr/SpeakerHigh';
export {SpeakerSlashIcon as MuteIcon} from '@phosphor-icons/react/dist/csr/SpeakerSlash';
export {FadersHorizontalIcon as FadersIcon} from '@phosphor-icons/react/dist/csr/FadersHorizontal';
export {SparkleIcon} from '@phosphor-icons/react/dist/csr/Sparkle';
export {ArrowsClockwiseIcon as RetryIcon} from '@phosphor-icons/react/dist/csr/ArrowsClockwise';
export {WarningCircleIcon as WarningIcon} from '@phosphor-icons/react/dist/csr/WarningCircle';
export {TrashIcon} from '@phosphor-icons/react/dist/csr/Trash';
export {PencilSimpleIcon as PencilIcon} from '@phosphor-icons/react/dist/csr/PencilSimple';
export {ArrowSquareOutIcon as ExpandIcon} from '@phosphor-icons/react/dist/csr/ArrowSquareOut';
export {FolderOpenIcon as FolderIcon} from '@phosphor-icons/react/dist/csr/FolderOpen';
export {ClockIcon} from '@phosphor-icons/react/dist/csr/Clock';
export {FileAudioIcon} from '@phosphor-icons/react/dist/csr/FileAudio';
export {ArrowUUpLeftIcon as UndoIcon} from '@phosphor-icons/react/dist/csr/ArrowUUpLeft';
export {SortAscendingIcon as SortIcon} from '@phosphor-icons/react/dist/csr/SortAscending';
export {CircleNotchIcon as SpinnerIcon} from '@phosphor-icons/react/dist/csr/CircleNotch';
export {SunIcon} from '@phosphor-icons/react/dist/csr/Sun';
export {MoonIcon} from '@phosphor-icons/react/dist/csr/Moon';
export {CaretRightIcon} from '@phosphor-icons/react/dist/csr/CaretRight';

export {MusicNotesIcon} from '@phosphor-icons/react/dist/csr/MusicNotes';
export {CodeIcon} from '@phosphor-icons/react/dist/csr/Code';
export {PlusIcon} from '@phosphor-icons/react/dist/csr/Plus';
export {MinusIcon} from '@phosphor-icons/react/dist/csr/Minus';
