import {useEffect,useRef,useState} from 'react';
import {AnimatePresence,motion} from 'motion/react';
import * as Menu from '@radix-ui/react-dropdown-menu';
import {ReferenceAudioCard,type ReferenceAudio} from './reference-audio';
import {Button,IconButton,Sheet} from './components';
import {MusicNotesIcon,CodeIcon,PlusIcon,MinusIcon,ClockIcon,FileAudioIcon,WaveformIcon,DownloadIcon,CopyIcon,CaretDownIcon,CheckIcon,ExpandIcon,RetryIcon,WarningIcon,XIcon} from './icons';
import {formatTime,type ReferenceSource} from './domain';
import './score-workspace.css';

type Score={id:string;title:string;source:ReferenceSource;mode:'full'|'melody';created:number;state:string;stage:string;hasAbc:boolean;artifacts:string[];warnings:string[];error?:string;duration?:number;reused?:boolean};
const activeStates=['queued','analyzing','rendering','cancelling'];
const storage='yue2-score-workspace-v1';
async function request<T>(path:string,body?:unknown):Promise<T>{const response=await fetch('/api/v1/scores'+path,body===undefined?{}:{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const result=await response.json();if(!response.ok)throw Object.assign(new Error(typeof result.detail==='string'?result.detail:'操作失败，请重试'),{status:response.status});return result}
function saved(){try{return JSON.parse(localStorage.getItem(storage)||'{}')}catch{return {}}}
export function ScoreSkeleton(){
 const ref=useRef<HTMLDivElement>(null);
 useEffect(()=>{const element=ref.current;if(!element)return;let visible=true;const sync=()=>{element.dataset.paused=String(!visible||document.hidden)};const observer=new IntersectionObserver(([entry])=>{visible=entry.isIntersecting;sync()});observer.observe(element);document.addEventListener('visibilitychange',sync);sync();return()=>{observer.disconnect();document.removeEventListener('visibilitychange',sync)}},[]);
 return <div ref={ref} className="score-skeleton" aria-hidden="true"><div className="skeleton-title"/><div className="skeleton-subtitle"/>{[0,1,2,3].map(row=><div className="skeleton-system" key={row}>{[0,1].map(staff=><div className="skeleton-staff" key={staff}><span className="skeleton-label"/><div className="skeleton-lines">{[0,1,2,3,4].map(i=><i key={i}/>)}<div className="skeleton-notes">{[0,1,2,3].map(i=><b key={i} style={{width:`${12+(i+row)%3*5}%`}}/>)}</div></div></div>)}</div>)}</div>}
export function ScoreWorkspace({active,onStatus}:{active:boolean;onStatus:(n:number)=>void}){
 const [initial]=useState(saved),[source,setSource]=useState<ReferenceSource|undefined>(initial.source),[audio,setAudio]=useState<ReferenceAudio|null>(null),[mode,setMode]=useState<'full'|'melody'>(initial.mode==='melody'?'melody':'full');
 const [selected,setSelected]=useState<string|null>(initial.selected??null),[items,setItems]=useState<Score[]>([]),[busy,setBusy]=useState(false),[sending,setSending]=useState(false),[error,setError]=useState(''),[connected,setConnected]=useState(true),[history,setHistory]=useState(false),[view,setView]=useState<'staff'|'abc'>('staff'),[abc,setAbc]=useState(''),[zoom,setZoom]=useState(100),[fold,setFold]=useState(false),[copied,setCopied]=useState(false),[missing,setMissing]=useState<ReferenceSource|null>(null),[wrap,setWrap]=useState(false);
 const pending=useRef<{requestId:string;source:ReferenceSource;mode:'full'|'melody'}|null>(null),loaded=useRef('');
 const current=items.find(r=>r.id===selected),running=!!current&&activeStates.includes(current.state),hasPages=!!current?.artifacts.some(a=>a.endsWith('.svg'));
 const changed=!!current&&(source?.id!==current.source.id||JSON.stringify(source?.range??null)!==JSON.stringify(current.source.range??null)||mode!==current.mode);
 async function refresh(){try{const next=await request<Score[]>('');setItems(next);onStatus(next.filter(r=>activeStates.includes(r.state)).length);setConnected(true)}catch{setConnected(false)}}
 useEffect(()=>{void refresh();const timer=setInterval(()=>void refresh(),2000);return()=>clearInterval(timer)},[]);
 useEffect(()=>{try{localStorage.setItem(storage,JSON.stringify({source,mode,selected}))}catch{}},[source,mode,selected]);
 useEffect(()=>{if(!current?.hasAbc)return;const id=current.id;if(loaded.current===id)return;let live=true;void request<{abc:string}>('/'+id+'/abc').then(result=>{if(live){loaded.current=id;setAbc(result.abc)}}).catch(e=>{if(live)setError(e.message)});return()=>{live=false}},[current?.id,current?.hasAbc]);
 useEffect(()=>{setAbc('');loaded.current='';setZoom(100)},[selected]);
 function onAudio(value:ReferenceAudio|null){setAudio(value);setSource(value?.source?{...value.source,range:value.range}:undefined)}
 async function submit(){if(!source||sending||busy)return;setSending(true);setError('');try{if(!pending.current||pending.current.mode!==mode||JSON.stringify(pending.current.source)!==JSON.stringify(source))pending.current={requestId:crypto.randomUUID(),source:structuredClone(source),mode};const result=await request<Score>('',pending.current);pending.current=null;setSelected(result.id);setView('staff');setFold(true);await refresh()}catch(e){const failure=e as Error&{status?:number};if(failure.status&&failure.status<500)pending.current=null;setError(failure.message+(pending.current?'；再次点击将确认同一份提交。':''))}finally{setSending(false)}}
 async function action(path:string){setError('');try{await request(path,{});await refresh()}catch(e){setError((e as Error).message)}}
 function open(item:Score){setSelected(item.id);setMode(item.mode);setSource(item.source);setAudio(null);setHistory(false);setFold(true);setView('staff');setError('')}
 function fresh(){setSelected(null);setAudio(null);setSource(undefined);setFold(false);setError('');pending.current=null}
 async function copy(){try{await navigator.clipboard.writeText(abc);setCopied(true);setTimeout(()=>setCopied(false),1800)}catch{setError('复制失败，请选择源码后手动复制。')}}
 const artifact=(name:string)=>`/api/v1/scores/${current?.id}/artifacts/${name}`;
 const pages=current?.artifacts.filter(a=>a.endsWith('.svg'))??[];
 return <section className="score-workspace" aria-label="谱曲工作台">
   <header className="score-page-header"><div className="score-page-title"><MusicNotesIcon size={25}/><div><h1>谱曲</h1><p>从音频提取旋律与和弦</p></div></div><div className="score-header-actions"><Button onClick={fresh}><PlusIcon/>新建分析</Button><Button onClick={()=>setHistory(true)}><ClockIcon/>历史记录{items.length>0&&<span className="score-count">{items.length}</span>}</Button></div></header>
   {!connected&&<div className="score-notice"><WarningIcon size={16}/>引擎连接中断，后台分析仍可能继续。<button onClick={()=>void refresh()}>重新连接</button></div>}
   <div className="score-input-card">
     {source&&<button className="score-input-summary" onClick={()=>setFold(!fold)} aria-expanded={!fold}><FileAudioIcon size={19}/><strong>{source.name}</strong><span>{source.range?`${formatTime(source.range[0])} — ${formatTime(source.range[1])}`:audio?`整首 · ${formatTime(audio.duration)}`:'整首分析'}</span><CaretDownIcon className={fold?'':'rotated'}/></button>}
      <div data-collapsed={fold&&Boolean(source)} className="score-input-body" inert={!!(fold&&source)} aria-hidden={!!(fold&&source)}><div><ReferenceAudioCard purpose="score" active={active&&!(fold&&source)} value={audio} source={source} onChange={onAudio} onBusyChange={setBusy} onMissing={value=>{setMissing(value);setAudio(null)}}/>{!source&&<p className="score-input-help">选择一首歌曲，或在波形上框选片段。原音频仅记录路径。</p>}</div></div>
     <div className="score-analysis-row"><div className="score-mode" role="group" aria-label="分析内容">{([['full','完整转谱'],['melody','仅旋律']] as const).map(([value,label])=><button key={value} aria-pressed={mode===value} onClick={()=>setMode(value)}>{label}</button>)}</div><span className="score-mode-hint">{mode==='full'?'旋律与和弦':'人声与器乐旋律'}</span>{running?<Button className="score-cancel" disabled={current.state==='cancelling'} onClick={()=>void action('/'+current.id+'/cancel')}><XIcon/>取消分析</Button>:<Button className="score-submit" disabled={!source||busy||sending||!connected} onClick={()=>void submit()}><WaveformIcon/>{sending?'提交中…':current?'重新分析':'开始分析'}</Button>}</div>
   </div>
   {error&&<div role="alert" className="score-notice error"><WarningIcon size={16}/><span>{error}</span><IconButton label="关闭错误" onClick={()=>setError('')}><XIcon/></IconButton></div>}
   <motion.div layout="position" className="score-result">
     <div className="score-result-toolbar"><div className="score-result-name"><MusicNotesIcon size={18}/><strong>{current?.title??'乐谱预览'}</strong>{changed&&<small>输入已更改 · 当前显示上次结果</small>}</div><div className="score-view-tabs" role="tablist" aria-label="乐谱显示格式">{([['staff','五线谱',MusicNotesIcon],['abc','ABC',CodeIcon]] as const).map(([id,label,Icon])=><button key={id} role="tab" aria-selected={view===id} tabIndex={view===id?0:-1} onKeyDown={e=>{if(['ArrowLeft','ArrowRight','Home','End'].includes(e.key)){e.preventDefault();const target=e.key==='Home'?'staff':e.key==='End'?'abc':view==='staff'?'abc':'staff';setView(target);e.currentTarget.parentElement?.querySelector<HTMLButtonElement>(`[aria-controls=score-view-${target}]`)?.focus()}}} aria-controls={'score-view-'+id} onClick={()=>setView(id)}><Icon size={16}/>{label}</button>)}</div><Menu.Root><Menu.Trigger asChild><Button className="score-export" disabled={!current?.hasAbc}><DownloadIcon/>导出<CaretDownIcon size={13}/></Button></Menu.Trigger><Menu.Portal><Menu.Content className="dropdown" align="end">{current?.hasAbc&&<Menu.Item asChild><a href={artifact('score.abc')} download={current.title+'.abc'}>ABC 源码</a></Menu.Item>}{current?.artifacts.filter(a=>a.endsWith('.pdf')||a.endsWith('.svg')||a.endsWith('.png')).map(name=><Menu.Item key={name} asChild><a href={artifact(name)} download={`${current.title}-${name}`}>{name.endsWith('.pdf')?'PDF · 全部页面':`${name.endsWith('.svg')?'SVG':'PNG'} · 第 ${Number(name.match(/\d+/)?.[0])} 页`}</a></Menu.Item>)}</Menu.Content></Menu.Portal></Menu.Root></div>
     <div className="score-result-meta"><span className={running?'score-live-label':''}>{running?<><span className="score-live-dot"/>{current.stage}</>:current?<>{current.state==='succeeded'?<CheckIcon size={14}/>:<WarningIcon size={14}/>} {current.stage}{current.reused?' · 已复用转谱缓存':''}</>:'分析完成后，可在两种视图之间切换'}</span>{current?.hasAbc&&<span>{current.mode==='full'?'旋律与和弦':'仅旋律'}{pages.length?` · ${pages.length} 页`:''}</span>}</div>
     {current?.state==='failed'&&<div className="score-notice error"><WarningIcon size={16}/><span>{current.hasAbc?'五线谱排版失败，ABC 已保留。':'音频分析失败，请检查任务详情。'}<details><summary>查看原因</summary>{current.error}</details></span>{current.hasAbc&&<Button onClick={()=>void action('/'+current.id+'/render')}><RetryIcon/>重试排版</Button>}</div>}
     <div className="score-stage" data-view={view}>
       <div className="score-paper-scroll" id="score-view-staff" role="tabpanel" hidden={view!=='staff'} tabIndex={0} aria-label="五线谱" aria-busy={running}>
        {running?<ScoreSkeleton/>:hasPages?<div className="score-pages" style={{width:`${zoom}%`}}>{pages.map((name,index)=><figure key={name}><img src={artifact(name)} alt={`${current?.title}，第 ${index+1} 页五线谱`} loading="lazy"/><figcaption>{index+1} / {pages.length}</figcaption></figure>)}</div>:<div className="score-blank"><div className="score-empty-icon"><MusicNotesIcon size={38} weight="thin"/></div><h2>{current?'谱面尚未就绪':'让旋律，清晰可见'}</h2><p>{current?.hasAbc?'可以切换到 ABC 查看已提取的内容。':current?'重新分析后，五线谱会呈现在这里。':'添加歌曲并开始分析，在这里阅读旋律与和弦。'}</p><div className="score-empty-features"><span><MusicNotesIcon size={16}/>双声部五线谱</span><span><CodeIcon size={16}/>ABC 源码</span><span><DownloadIcon size={16}/>多格式导出</span></div></div>}
       </div>
       <div className="score-abc-view" id="score-view-abc" role="tabpanel" hidden={view!=='abc'} aria-label="ABC 源码"><div className="score-code-tools"><span>ABC NOTATION <small>只读</small></span><div><button aria-pressed={wrap} onClick={()=>setWrap(!wrap)}>自动折行</button><button disabled={!abc} onClick={()=>void copy()}>{copied?<CheckIcon size={14}/>:<CopyIcon size={14}/>} {copied?'已复制':'复制全部'}</button></div></div><div className={'score-code-scroll '+(wrap?'wrap':'')} tabIndex={0}>{abc?<pre>{abc.split('\n').map((line,index)=><div key={index}><span aria-hidden="true">{index+1}</span><code>{line||' '}</code></div>)}</pre>:running?<div className="abc-skeleton" aria-label="正在提取 ABC">{[76,54,88,64,93,70,81,58].map((width,i)=><i key={i} style={{width:width+'%'}}/>)}</div>:<p className="score-code-empty">{current?'此任务还没有可用的 ABC。':'分析完成后，这里会显示 ABC 源码。'}</p>}</div></div>
       <AnimatePresence>{view==='staff'&&hasPages&&!running&&<motion.div className="score-zoom" style={{x:"-50%"}} initial={{opacity:0,y:5}} animate={{opacity:1,y:0}} exit={{opacity:0,y:4}}><IconButton label="缩小谱面" disabled={zoom<=50} onClick={()=>setZoom(z=>Math.max(50,z-25))}><MinusIcon size={16}/></IconButton><span>{zoom===100?'适应宽度':zoom+'%'}</span><IconButton label="放大谱面" disabled={zoom>=200} onClick={()=>setZoom(z=>Math.min(200,z+25))}><PlusIcon size={16}/></IconButton><i/><IconButton label="适应宽度" onClick={()=>setZoom(100)}><ExpandIcon size={17}/></IconButton></motion.div>}</AnimatePresence>
     </div>
     {current&&current.warnings.length>0&&<details className="score-warnings"><summary>识别提示 · {current.warnings.length}</summary>{current.warnings.map((w,i)=><p key={i}>{String(w)}</p>)}</details>}
   </motion.div>
   <Sheet open={history} onClose={()=>setHistory(false)} title="谱曲记录" subtitle="已保存的乐谱可随时打开，不需要重新分析。"><div className="score-history-list">{items.length?items.map(item=><button key={item.id} onClick={()=>open(item)} className={item.id===selected?'selected':''}><span className="score-history-icon"><MusicNotesIcon size={23}/></span><span><strong>{item.title}</strong><small>{item.mode==='full'?'完整转谱':'仅旋律'} · {new Date(item.created).toLocaleDateString('zh-CN')}</small></span><small>{item.stage}</small></button>):<p className="setting-help">还没有分析记录。添加一首歌曲开始。</p>}</div></Sheet>
   <Sheet open={!!missing} onClose={()=>{setMissing(null);setSource(undefined)}} title="原音频无法读取" subtitle="谱面和 ABC 仍可查看。重新分析或试听需要补选音频。" center footer={<><Button onClick={()=>{setMissing(null);setSource(undefined);setFold(false);setTimeout(()=>document.querySelector<HTMLButtonElement>('.score-workspace .add-reference')?.click(),350)}}>重新选择</Button><Button onClick={()=>{setMissing(null);setSource(undefined)}}>放弃添加</Button></>}><p className="score-missing-path">{missing?.path}</p></Sheet>
 </section>
}

